apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: niqkgrtah-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1d2f603d6f.xkgu.p3.openshiftapps.com/rhtap/rhtap-qe-go:9e67f17022fe97d6df9ecaa594795f62fb1bad1a@sha256:85d5ce47cfa3594c7446f6b604e7a65c0c931cf289a20c4ca9fc03cbf513e43f
          name: container-image
